### PR TITLE
feat: upload binary using node major tag

### PR DESCRIPTION
**Pull request by robertsLando**

### CODE REVIEW

**Review by n1ru4l — APPROVED** [review]

**Comment by n1ru4l** [comment]
@robertsLando I don't think that this PR should close https://github.com/robertsLando/pkg-binaries/issues/10

**Comment by robertsLando** [comment]
@n1ru4l Partially, I have removed the link. Anyway I don't know how we could make that support, I mean build for macos and win, we would need node docker base images that I don't know if they exists. Alpine and linux are already supported

**Comment by robertsLando** [comment]
Let's see how this goes: https://github.com/robertsLando/pkg-binaries/runs/1122291781?check_suite_focus=true

**Comment by n1ru4l** [comment]
> Partially as we also spoke about this but I have removed the link. Anyway I don't know how we could make that support, I mean build for macos and win, we would need node docker base images that I don't know if they exists.

You can build the binaries on "raw" action workers outside docker see https://github.com/dungeon-revealer/dungeon-revealer/blob/b9e2a13a4d3c86c2a53d7aa4e027d20ef95186a8/.github/workflows/build-binaries.yml#L10-L51 as a reference. Anyways lets continue discussion in the issue :)

**Comment by robertsLando** [comment]
the run has fail, could you chek it? @n1ru4l

**Comment by n1ru4l** [comment]
See https://github.com/n1ru4l/pkg-fetch/commit/bcf418c66bb1419c380f203cb34d49905e66c5ef

**Pull request merged**
